query Wishlist {
  wishlist {
    ...ProductCard
  }
}

query WishlistIds {
  wishlistIds
}

mutation ToggleWishlist($productId: Int!) {
  toggleWishlist(product_id: $productId) {
    product_id
    is_wishlisted
    wishlist_count
  }
}
